# Generated by Django 4.2.28 on 2026-02-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in USD (0 means free)', max_digits=10),
        ),
    ]
